sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-23
  - android-26
before_install:
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
# NDK Path: https://stackoverflow.com/a/43593944
- cd $HOME
- wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O $HOME/android-sdk.tgz
- mkdir android
- unzip android-sdk.tgz -d android/sdk
- export PATH=$PATH:$HOME/android/sdk/tools:$HOME/android/sdk/tools/bin
- cd build/

# NDK Path: https://stackoverflow.com/a/43593944
install:
- echo y | sdkmanager 'ndk-bundle'
- echo y | sdkmanager 'cmake;3.6.3155560'
- export ANDROID_HOME=$HOME/android/sdk
- export ANDROID_NDK_HOME=$HOME/android/sdk/ndk-bundle


licenses:
- android-sdk-license-.+
- '.+'

script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
notifications:
  email: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: IcG5jr5SUYGB9LiBChfXF9HfHMEYwrpxMDWn6xC/xpv8IHJGcPV5BjfiwnEEjr2OgZEcVIA1rtHH8eaBiF/zW8b3NXXErcVOxKMoNFT42LuzGY3ZE7d7G9tr9MsT5g70uyyWzWlI5vlhbdNhTeo4v6w5j3ewl6eIBIMxLUqHza+BSpiA+SQ3hWkl1zQyfN3stcXLMcf/OiIKMVplpmugL3aYPAXWGF5mHaPxO7P5/SJXgmDNoYw+VJ2pk4G7pC7jnf5deXNHll1GIvfqNhuiezUV41xMpwfYyawMGCU732UFqZHLn8hki4lu7YEk1dUI0l/FP6uHGnpMZxvObEJGd8QuftLzEqwR6r2Uwg5J5DjvWTgqehorugE1yDTjT0Zq9DUQws7hALIa36OjJvoDDoD0YW+9Bs31fIb6a/1jHJrcp0mFE1w2M6WxW12fJtQD1krs2MV/yv0j8HnvRH6DCl4siu7b0csHI45JZ7McAIVpNnz0GGcQGnPdNubv8QYGikJLppWFsggjNB5eLF+CwgLvSDZnfGvc90Fi0dialrdIbam2+ZgwaluD/TWNFwLtDTanzLIuTkWfbPE2eViSAMR3bU4ZXpHZPEDXSsCdd5lrCka9dxAWBfJ73kUNy+ViQ3m7Rji8l4GWne43nb5b2VF1a9zbVIABwMEv1JOhSrk=
  file: app/build/outputs/apk/app-debug.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: PhoenixRRDS/AIRYL
after_success:
- sh set_tags.sh
